### ISSUE TITLE
Can't access web-app

### ISSUE THREAD

**Issue by hazbiy97** [horeaporutiu/blockchainbean2#4]
Hello i'm really thankful for this tutorial, and forgive me because i'm complete beginner with this but i can't seems to access localhost:3000/explorer/ (i don't know which framework you're using in this project because it's not like angular or react for me). after running npm start on web-app, nothing after that and i still can't access the explorer.

I'm using this for my bachelor thesis so if you can help me i will really appreciate that 

![image](https://user-images.githubusercontent.com/34585999/53801929-19506980-3f73-11e9-9704-a1e13309357f.png)

i'm running on macOS 10.13
npm 5.6
node 8.11.3
yo 2.0.5
docker 18.09.1
docker-compose 1.23.2

**Comment by hazbiy97** [comment]
ooops sorry it seems i can't start the web app by using vs terminal

**Comment by horeaporutiu** [comment]
so you must start the app on your terminal, then go into your browser to see the web app. If you have solved this problem, then I will close the issue.

**Comment by renkarnation** [comment]
can I ask you a question?
where can I find the loopback openAPI, I can't seem to find it

**Comment by horeaporutiu** [comment]
can you be more specific?

After you run `npm start`, your web-app will be running on http://localhost:8080/explorer

This is the same as my sample Loopback API that is running here: http://blockchainbeans2.mybluemix.net/explorer/

Documentation for Loopback can be found here: https://loopback.io/

Did I answer your question? If not, please be more specific in exactly what you are looking for.

**Comment by renkarnation** [comment]
I see, Thank you very much.
