### ISSUE TITLE
IBM Cloud Kubernetes

### ISSUE THREAD

**Issue by hazbiy97** [horeaporutiu/blockchainbean2#5]
Is there any alternative for ibm cloud kubernetes? i'm using blockchain IBM for my thesis so it doesn't really matter if i'm not using IBM blockchain. I don't have any access to credit card and so i can't create free trial on the cloud 

![image](https://user-images.githubusercontent.com/34585999/53804388-f5dced00-3f79-11e9-8d6e-38f305d4cbbd.png)

**Comment by horeaporutiu** [comment]
You can any Kubernetes service you want - Google, Microsoft and AWS (Amazon) each have their own. I'm pretty sure you can create a free cluster on their cloud, and use that cluster to launch your IBM Blockchain service. Note that I have not tried this, but I know this should be possible.

**Comment by hazbiy97** [comment]
ohh really? so i'm at pinch right now. if i may ask, what does cloud's function in this project? does it impossible to run blockchain without cloud services? i'm trying to understand how blockchain works in supply chain management so i'm really new at this.

**Comment by horeaporutiu** [comment]
@hazbiy97 

Cloud is great if you want to scale your network easily. Also, the cloud adds monitoring and a nice way to view your network. I'd say it's not 100% necessary, it just makes your network smoother and easier to manage. For a production network, which exists to provide mission-critical data to companies, I'd say a cloud service is much more of a necessity, but for just starting out, it's not 100% necessary.
